# Generated by Django 2.1.10 on 2019-07-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_code', models.CharField(max_length=4)),
                ('symbol', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=50)),
                ('industry1', models.CharField(max_length=10)),
                ('industry2', models.CharField(max_length=20)),
                ('count_per', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('marketcap', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('marketcap_per', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
