# Generated by Django 2.1.10 on 2019-07-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vietnam_research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='marketcap',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
