# Generated by Django 2.1.10 on 2019-07-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vietnam_research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry1', models.CharField(max_length=10)),
                ('industry_class', models.IntegerField()),
            ],
        ),
    ]
