# Generated by Django 2.1.10 on 2019-07-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vietnam_research', '0003_auto_20190723_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='marketcap_percentage',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
