# Generated by Django 2.1.10 on 2019-07-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_chartjs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangotesttable',
            name='question_text',
        ),
        migrations.AddField(
            model_name='djangotesttable',
            name='month_code',
            field=models.CharField(default='xxx', max_length=3),
        ),
        migrations.AddField(
            model_name='djangotesttable',
            name='sales',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
