# Generated by Django 2.1.10 on 2019-07-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_chartjs', '0002_auto_20190715_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangotesttable',
            name='sales',
            field=models.IntegerField(default=0),
        ),
    ]
